  
language: node_js
node_js:
  - '10'
install:
  - npm install
before_script:
  - npm run build
script:
  - npm test
before_deploy:
  - npm install
  - npm run build
deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      repo: revelrylabs/react-uniqueid
      tags: true
      node: '10'
    skip_cleanup: true
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release
    on:
      repo: revelrylabs/react-uniqueid
      node: '10'
